export { default as ArrowDown } from './arrow-down.svg'
export { default as Google } from './google.svg'
export { default as Illustration } from './illustration.svg'
export { default as Logo } from './logo.svg'
export { default as Menu } from './menu.svg'
export { default as Plus } from './plus.svg'
